### PR TITLE
(`c2rust-analyze`) Handle inline `const` refs, including string literals

### LINKED ISSUE #837: (`c2rust-analyze`) Handle string literals
Currently, `c2rust-analyze` can't handle any string literals, such as `""` or `b""`:

```shell
callgraph traversal order:
  DefId(0:3 ~ string_casts[c5c4]::f)
visit_statement(StorageLive(_1))
visit_statement(_1 = const "")
thread 'rustc' panicked at 'unexpected pointer type in &str', c2rust-analyze/src/context.rs:506:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d394408fb38c4de61f765a3ed5189d2731a1da91/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/d394408fb38c4de61f765a3ed5189d2731a1da91/library/core/src/panicking.rs:142:14
   2: c2rust_analyze::context::label_no_pointers::{{closure}}
             at ./src/context.rs:503:9
   3: c2rust_analyze::labeled_ty::LabeledTyCtxt<L>::label
             at ./src/labeled_ty.rs:157:21
   4: c2rust_analyze::context::label_no_pointers
             at ./src/context.rs:502:5
   5: <rustc_middle::mir::syntax::Operand as c2rust_analyze::context::TypeOf>::type_of
             at ./src/context.rs:494:41
   6: <&T as c2rust_analyze::context::TypeOf>::type_of
             at ./src/context.rs:464:9
   7: c2rust_analyze::context::AnalysisCtxt::type_of
             at ./src/context.rs:241:9
   8: c2rust_analyze::context::AnalysisCtxt::type_of_rvalue
             at ./src/context.rs:304:36
   9: c2rust_analyze::dataflow::type_check::TypeChecker::visit_statement
             at ./src/dataflow/type_check.rs:233:30
  10: c2rust_analyze::dataflow::type_check::visit
             at ./src/dataflow/type_check.rs:388:13
  11: c2rust_analyze::dataflow::generate_constraints
             at ./src/dataflow/mod.rs:326:5
  12: c2rust_analyze::run
             at ./src/main.rs:480:45
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Fixing this is a prerequisite to #833.

### PR DESCRIPTION
**Pull request by kkysen**
Fixes #837.

This only handles `const` refs that are inline and thus local to a function, as determined by being `ConstantKind::Val`.  Thus, this handles string literals like `""` (`inline_str`) and `b""` (`inline_bstr`), which is the main thing we're trying to support.

This PR also adds tests for other similar string usages, though they're not handled and turned off for now.  The outline cases, where the `const` ref/string literal is used through a named constant, aren't handled, as they are globally accessible and that makes them more complex.  Since supporting them isn't necessary for string literals, which is the main usage in `lighttpd-rust`.

### CODE REVIEW

**Comment by kkysen** [comment]
I'm not sure if/how this PR should add exact `READ | OFFSET_ADD` permissions for string literals (and `READ` permissions for scalar literal refs).

File: c2rust-analyze/src/context.rs [hunk 1]
```diff
@@ -98,13 +98,15 @@ pub struct AnalysisCtxt<'a, 'tcx> {
...
     pub rvalue_tys: HashMap<Location, LTy<'tcx>>,
+    pub const_tys: HashMap<ConstantKind<'tcx>, LTy<'tcx>>,
     next_ptr_id: NextLocalPointerId,
 }
 
 pub struct AnalysisCtxtData<'tcx> {
     local_tys: IndexVec<Local, LTy<'tcx>>,
     addr_of_local: IndexVec<Local, PointerId>,
     rvalue_tys: HashMap<Location, LTy<'tcx>>,
+    const_tys: HashMap<ConstantKind<'tcx>, LTy<'tcx>>,
```
Comment (spernsteiner) [inline c2rust-analyze/src/context.rs:109]: It looks to me like we could use `rvalue_tys` for this instead of adding a new map.

**Comment by spernsteiner** [comment]
>I'm not sure if/how this PR should add exact `READ | OFFSET_ADD` permissions for string literals

I think the best approach for this is to assign `PointerId`s to these literals (as you've implemented here), set up the permissions/flags for those `PointerId`s in the initial `Assignment` prior to running `dataflow` and `borrowck`, and assert at the end that the permissions/flags weren't modified.  This will catch cases where the program tries to mutate a string literal (or other constant) and will stop us from trying to generate a bogus rewrite, like trying to turn `"foo"` into `&mut str`.

**Comment by kkysen** [comment]
> assert at the end that the permissions/flags weren't modified

If I do it this way, would it make more sense to keep `const_tys` separate from `rvalue_tys`?

File: c2rust-analyze/src/dataflow/type_check.rs [hunk 2]
```diff
@@ -484,5 +504,11 @@ pub fn visit<'tcx>(
         );
     }
 
+    for (&constant, const_lty) in &acx.const_tys {
+        let _ptr_id = const_lty.label;
+        let _expected_perms = const_perms(constant);
+        // TODO: check that perms match the expected ones
+    }
```
Comment (kkysen) [inline c2rust-analyze/src/dataflow/type_check.rs:511]: How can I lookup the `PermissionSet` of a `PointerId` after dataflow typeck has run?

Comment (spernsteiner) [reply c2rust-analyze/src/dataflow/type_check.rs]: That mapping is in the `Assignment`

File: c2rust-analyze/src/main.rs [hunk 3]
```diff
@@ -454,6 +454,7 @@ fn run(tcx: TyCtxt) {
             assert_eq!(local, l);
         }
 
+        let mut const_ref_tys = HashMap::new();
```
Comment (aneksteind) [inline c2rust-analyze/src/main.rs:457]: why not insert into the `acx` map directly?

**Comment by aneksteind** [comment]
> If I do it this way, would it make more sense to keep const_tys separate from rvalue_tys?

@kkysen why not go about it this way, i.e. why is `const_tys` used instead?

**Comment by kkysen** [comment]
I was going to change it back to using `rvalue_tys`, but if I need to iterate through the constant ones at the end to check the permissions weren't modified, then it's a lot simpler if there's a separate map.

**Comment by aneksteind** [comment]
I think it would be cleaner to keep the `rvalue_tys` dict alone and instead have logic that checks permissions and matches against the `RValue` ty and checks there. If we want to check similar things in the future we would end up adding another map to the context to maintain the pattern and I don't think that'd be the best design

**Comment by kkysen** [comment]
There's not really a way to tell an `LTy` came from a constant, though, right?  I'm not sure how to retrieve that information back.
.

File: c2rust-analyze/src/main.rs (hunk 3 above)
Comment (kkysen) [reply c2rust-analyze/src/main.rs:457]: There'd be multiple mutable references to `acx` then, due to `acx.rvalue_tys`..  It'd probably be better to construct the `AnalysisCtxt` with the maps already constructed, but that'd be a bit more of a change, so I just did it this way for now.

**Comment by kkysen** [comment]
@spernsteiner, the post-typeck check is erroring, saying the permissions have expanded from `READ | OFFSET_ADD` to `READ | UNIQUE | OFFSET_ADD`.  Is this correct?

**Comment by kkysen** [comment]
@spernsteiner, also, do you think any `FileCheck` tests are needed for this, or is the post-typeck check that the permissions are as expected more than enough?

File: c2rust-analyze/src/main.rs (hunk 3 above)
Comment (kkysen) [reply c2rust-analyze/src/main.rs:457]: Oh, well it might not have been that specifically then, but there definitely was a borrow checker error.  I tried this way first but it didn't work.

File: c2rust-analyze/src/context.rs (hunk 1 above)
Comment (kkysen) [reply c2rust-analyze/src/context.rs]: Discussion moved here: https://github.com/immunant/c2rust/pull/886#issuecomment-1517568518.

File: c2rust-analyze/src/util.rs [hunk 4]
```diff
@@ -348,3 +348,6 @@ pub fn is_null_const(constant: Constant) -> bool {
         _ => false,
     }
 }
+
+pub trait PhantomLifetime<'a> {}
```
Comment (aneksteind) [inline c2rust-analyze/src/util.rs:352]: why is this necessary?

File: c2rust-analyze/src/dataflow/type_check.rs [hunk 5]
```diff
@@ -465,6 +465,10 @@ pub fn visit<'tcx>(
         equiv_constraints: Vec::new(),
     };
 
+    for (ptr, perms) in acx.const_ref_perms() {
+        tc.constraints.add_all_perms(ptr, perms);
```
Comment (aneksteind) [inline c2rust-analyze/src/dataflow/type_check.rs:469]: why not add the constraints as you see consts in `visit_rvalue`?

File: c2rust-analyze/src/main.rs [hunk 6]
```diff
@@ -489,6 +489,18 @@ fn run(tcx: TyCtxt) {
...
+                    Rvalue::Use(Operand::Constant(c)) => {
+                        // Constants can include, for example, `""` and `b""` string literals.
+                        if let ConstantKind::Val(_, ty) = c.literal && ty.is_ref() {
+                            // The [`Constant`] is an inline value and thus local to this function,
+                            // as opposed to a global, named `const`s, for example.
+                            // This might miss local, named `const`s,
+                            acx.assign_pointer_ids(ty)
+                        } else {
+                            // TODO: Handle global, named `const`s.
+                            continue;
```
Comment (aneksteind) [inline c2rust-analyze/src/main.rs:501]: should we emit a warning here?

**Review by aneksteind — COMMENTED** [review]
I'm not sure why `PhantomLifetime` is necessary. Without knowing for sure it seems like an unnecessary complication. I also think the vector of locations for const refs is similarly unnecessary in that the permissions can be checked in another visit of the body after the permissions have been propagated (maybe in the `borrowck` phase or somewhere in between) in combination with adding constraints during the `dataflow` visitation.

**Review by aneksteind — APPROVED** [review]
Despite my comments, however, I think this looks good enough. Insofar as the points made above are valid, consider reducing the complexity slightly.

File: c2rust-analyze/src/main.rs (hunk 6 above)
Comment (kkysen) [reply c2rust-analyze/src/main.rs:501]: Yeah maybe.  I think this `continue` eventually turns into the same `label_no_pointers` error, which isn't very descriptive.  We should only warn on references, though, as non-references will be fine in the `label_no_pointers` later on.

**Comment by kkysen** [comment]
> I'm not sure why `PhantomLifetime` is necessary. Without knowing for sure it seems like an unnecessary complication.

It was needed due to how lifetimes and `impl Trait` work where I can't do multiple `impl Trait + 'a + 'b`s and have it work, but I can do `impl Trait + PhantomLifetime<'a> + 'b` and that works.  It's similar to `PhantomData` and type parameters, but with lifetimes.

**Comment by kkysen** [comment]
> I also think the vector of locations for const refs is similarly unnecessary in that the permissions can be checked in another visit of the body after the permissions have been propagated (maybe in the `borrowck` phase or somewhere in between) in combination with adding constraints during the `dataflow` visitation.

Do you mean re-iterating through `BasicBlock`s, `Statement`s, `Rvalue`s, etc. to find the `Constant`s again?  Why is that better than doing it once and storing the result?

File: c2rust-analyze/src/context.rs [hunk 7]
```diff
@@ -98,13 +114,44 @@ pub struct AnalysisCtxt<'a, 'tcx> {
...
 }
 
+impl<'a, 'tcx> AnalysisCtxt<'_, 'tcx> {
+    pub fn const_ref_tys(&'a self) -> impl Iterator<Item = LTy<'tcx>> + 'a {
+        self.const_ref_locs.iter().map(|loc| self.rvalue_tys[loc])
+    }
+
+    pub fn const_ref_perms(
+        &'a self,
+    ) -> impl Iterator<Item = (PointerId, PermissionSet)> + PhantomLifetime<'tcx> + 'a {
```
Comment (spernsteiner) [inline c2rust-analyze/src/context.rs:131]: Is the `PhantomLifetime<'tcx>` actually necessary here?  I don't think the returned iterator borrows anything with lifetime `'tcx`.  `self.const_ref_tys()` returns an iterator that doesn't borrow `'tcx`, and the closure provided to `map` doesn't capture anything.

File: c2rust-analyze/src/util.rs (hunk 4 above)
Comment (spernsteiner) [inline c2rust-analyze/src/util.rs:352]: Should this be `trait PhantomLifetime<'a>: 'a {}` or something like that?  As-is, it seem like it doesn't constrain anything.

File: c2rust-analyze/src/context.rs (hunk 7 above)
Comment (kkysen) [reply c2rust-analyze/src/context.rs:131]: It is.  `self.const_ref_tys()` returns `LTy<'tcx>`s, and so I need that `'tcx` in the return type somewhere.  Since there's no more `LTy`, I need to stick it somewhere.

File: c2rust-analyze/src/util.rs (hunk 4 above)
Comment (kkysen) [reply c2rust-analyze/src/util.rs:352]: I don't think so?  Someone suggested this online when I was searching up the lifetime error.  Adding a `: 'a` makes it not compile.  I think the point of the `PhantomLifetime` is just to mark that `'a` is used.  Just like there's

```rust
pub struct PhantomData<T: ?Sized>;
```

**Comment by kkysen** [comment]
> an invariant of location being present in the index operations

What do you mean by this?  That `const_ref_locs`'s `Location`s are present in `rvalue_tys`?  That seems like a pretty simple invariant.  Or I might be misunderstanding.

File: c2rust-analyze/src/util.rs (hunk 4 above)
Comment (kkysen) [reply c2rust-analyze/src/util.rs:352]: See https://github.com/immunant/c2rust/pull/886#discussion_r1174153441.  It'd due to Rust not letting you add multiple lifetimes (at least correctly?) to an `impl Trait`.  I tried many other ways, but nothing worked, and I saw someone suggest this and it worked perfectly.

File: c2rust-analyze/src/main.rs (hunk 6 above)
Comment (kkysen) [reply c2rust-analyze/src/main.rs]: I made it into an error here: 6a0608331dfc43a9a429f7f6f73847621fb89ee6.  It'll turn into an error eventually in `label_no_pointers` anyways, and erroring here gives a much clearer error.
