### PR TITLE
transpile: Import `num_traits::Float` for method calls on `f128`

### LINKED ISSUE #1690: C2Rust generates calls to `f128` float methods without importing required traits
C2Rust generates Rust code that calls floating-point methods on `f128` (e.g., `is_infinite`, `is_sign_positive`) without importing the traits that provide these methods.
As a result, the generated Rust code fails to compile unless the user manually adds the required trait import.
**Reproducer**
```c
#include <stdio.h>
#include <math.h>

int main(void) {
    long double huge = __builtin_huge_val();
    printf("huge_val: Input=(none), Result=%s\n",
           isinf(huge) ? "INF" : "NOT_INF");
    return 0;
}
```
**Transpiled Rust**
```rust
#![allow(
    dead_code,
    non_camel_case_types,
    non_snake_case,
    non_upper_case_globals,
    unused_assignments,
    unused_mut
)]
extern "C" {
    fn printf(__format: *const ::core::ffi::c_char, ...) -> ::core::ffi::c_int;
}
unsafe fn main_0() -> ::core::ffi::c_int {
    let mut huge: ::f128::f128 = ::f128::f128::new(::core::f64::INFINITY);
    printf(
        b"huge_val: Input=(none), Result=%s\n\0" as *const u8
            as *const ::core::ffi::c_char,
        if if huge.is_infinite() {
            if huge.is_sign_positive() { 1 } else { -1 }
        } else {
            0
        } != 0
        {
            b"INF\0" as *const u8 as *const ::core::ffi::c_char
        } else {
            b"NOT_INF\0" as *const u8 as *const ::core::ffi::c_char
        },
    );
    return 0 as ::core::ffi::c_int;
}
pub fn main() {
    unsafe { ::std::process::exit(main_0() as i32) }
}
```
**Observed Behavior**
The generated Rust code fails to compile:
```
error[E0599]: no method named `is_infinite` found for struct `f128`
error[E0599]: no method named `is_sign_positive` found for struct `f128`
```
The compiler indicates that these methods are provided by traits such as:
```
num_traits::float::Float
```
but the generated code does not import them.
**Expected Behavior**
C2Rust should generate the necessary trait imports when emitting calls to trait-provided floating-point methods on `f128`.
**Environment**
- c2rust version: v0.21.0
- platform: Ubuntu 24.04
- Rust: nightly-2022-08-08
- Clang version: 17.0.6

### PR DESCRIPTION
**Pull request by Rua**
- Fixes #1690.

### CODE REVIEW

File: c2rust-transpile/src/translator/builtins.rs [hunk 1]
```diff
@@ -723,6 +723,26 @@ impl<'c> Translation<'c> {
...
+    fn import_num_traits(&self, arg_id: CExprId) -> TranslationResult<()> {
+        let arg_type_id = self.ast_context[arg_id]
+            .kind
+            .get_qual_type()
+            .ok_or_else(|| format_err!("bad arg type"))?;
+        let arg_type_kind = &self.ast_context.resolve_type(arg_type_id.ctype).kind;
+
+        match arg_type_kind {
+            CTypeKind::LongDouble | CTypeKind::Float128 => {
+                self.use_crate(ExternCrate::NumTraits);
```
Comment (ahomescu) [inline c2rust-transpile/src/translator/builtins.rs:749]: Was this not needed before because there's a cast after? Or how did this work before?

**Review by ahomescu — APPROVED** [review]

File: c2rust-transpile/src/translator/builtins.rs (hunk 1 above)
Comment (Rua) [reply c2rust-transpile/src/translator/builtins.rs:749]: I'm not sure it ever worked. These methods are not inherent methods of `f128`, they are provided by the `Float` trait. So without importing that, you just get a compile error.

Comment (kkysen) [reply c2rust-transpile/src/translator/builtins.rs:749]: I don't think we ever tested `f128` stuff much before, so that was probably the case.

**Review by kkysen — APPROVED** [review]
