### PR TITLE
Fix memory leaks in `analysis/test`

### LINKED ISSUE #681: Fix non-intentional memory leaks in `analysis/test`
This is related to #680 (fixing UB).  There are also a bunch of non-intentional memory leaks in `analysis/test`.  These are not UB, so they shouldn't be causing any unexpected behavior, but there's no good reason to have them, and they clutter up the `miri` output when looking for UB.  We should only keep the intentional leaks that are there for testing how we handle leaks.

### PR DESCRIPTION
**Pull request by kkysen**
Fixes #681.

This fixes all of the memory leaks in `analysis/test`.

There was one that was intentional (`no_owner(0)`), but I freed that in `main_0` immediately after the `no_owner(0)` call instead.

### CODE REVIEW

File: analysis/test/src/pointers.rs [hunk 1]
```diff
@@ -508,6 +516,7 @@ unsafe fn main_0(mut argc: libc::c_int, mut argv: *mut *mut libc::c_char) -> lib
     analysis2();
     inter_function_analysis();
     no_owner(0i32);
+    free(global as *mut libc::c_void);
```
Comment (kkysen) [inline analysis/test/src/pointers.rs:519]: The leak in `no_owner` when called with `no_owner(0)` is intentional.  Should it be freed in `main_0`, or is it intentional to completely leak it?

File: analysis/test/src/pointers.rs [hunk 2]
```diff
@@ -340,6 +343,7 @@ pub unsafe extern "C" fn test_arg() {
     let mut s = malloc(::std::mem::size_of::<S>() as libc::c_ulong);
     foo(s);
     let t = s;
+    free(s as *mut libc::c_void);
```
Comment (kkysen) [inline analysis/test/src/pointers.rs:346]: Should `t` be freed instead of `s`?

File: analysis/test/src/pointers.rs [hunk 3]
```diff
@@ -355,6 +359,7 @@ pub unsafe extern "C" fn foo_rec(n: i32, bar: *mut libc::c_void) -> *mut libc::c
 pub unsafe extern "C" fn test_arg_rec() {
     let mut s = malloc(::std::mem::size_of::<S>() as libc::c_ulong);
     let t = foo_rec(3, s);
+    free(s as *mut libc::c_void);
```
Comment (kkysen) [inline analysis/test/src/pointers.rs:362]: Should `t` be freed instead of `s`?

File: analysis/test/src/pointers.rs [hunk 4]
```diff
@@ -79,6 +80,7 @@ pub unsafe extern "C" fn simple() {
     recur(3, x);
     let s = *y;
     *x = s;
+    free(x2 as *mut libc::c_void);
```
Comment (aneksteind) [inline analysis/test/src/pointers.rs:83]: why is this necessary as opposed to freeing `x`?

File: analysis/test/src/pointers.rs (hunk 2 above)
Comment (aneksteind) [reply analysis/test/src/pointers.rs:346]: if they're the same address, does it make a difference?

File: analysis/test/src/pointers.rs (hunk 4 above)
Comment (aneksteind) [reply analysis/test/src/pointers.rs:83]: oh, i see, because x is reassigned

File: analysis/test/src/pointers.rs (hunk 1 above)
Comment (aneksteind) [reply analysis/test/src/pointers.rs:519]: i think what you have here is fine

File: analysis/test/src/pointers.rs (hunk 2 above)
Comment (aneksteind) [reply analysis/test/src/pointers.rs:346]: there was no particular intention, so this is fine

File: analysis/test/src/pointers.rs (hunk 3 above)
Comment (aneksteind) [reply analysis/test/src/pointers.rs:362]: this is fine

**Review by aneksteind — APPROVED** [review]
