### PR TITLE
Handle C decls with zero ending row/col

### LINKED ISSUE #1545: `--emit-c-decl-map` fails on `zstd` and `python2` in `slice_decl_with_fixups`
`--emit-c-decl-map` is [failing](https://github.com/immunant/c2rust/actions/runs/20843742204/job/59882927605?pr=1541#step:9:44) on `zstd` and `python2` in `slice_decl_with_fixups`.

See https://github.com/immunant/c2rust/pull/1541#issuecomment-3727513744

### PR DESCRIPTION
**Pull request by fw-immunant**
* Fixes #1545.

### CODE REVIEW

**Comment by fw-immunant** [comment]
If I should remove the test change in favor of other changes that might supersede it, let me know.

File: c2rust-transpile/src/c_ast/mod.rs [hunk 1]
```diff
@@ -344,6 +344,30 @@ impl TypedAstContext {
             // functions, because the variables will not be top-level decls. But it can occur
             // for macros defined inside functions, since all macros are top-level decls!
             let is_nested = end_loc < prev_end_loc;
+
+            // Clang emits declarations of builtins (and opaque types such as when encountering
+            // `struct undeclared *`) at their first usage site. This means that they are usually
+            // nested within another function, and (at least with how the C AST is  currently
```
Comment (kkysen) [inline c2rust-transpile/src/c_ast/mod.rs]:
```suggestion
            // nested within another function, and (at least with how the C AST is currently
```

**Review by kkysen — APPROVED** [review]
> If I should remove the test change in favor of other changes that might supersede it, let me know.

Could you cherry-pick 5946368 instead?  It just enables it for all of them.

**Review by kkysen — APPROVED** [review]
