### PR TITLE
Fix issue #1509 by improving handling of unused expression side effects

### LINKED ISSUE #1507: About the transaction output bug
Original C code:

```c
assert(writechar('A', &len) == 1);  
assert(len == 1);                    
```

c2rust output:

```rust
if writechar('A'...) == 1 {} else { __assert_fail(...); }
'c_2796: {
    if writechar('A'...) == 1 {} else { __assert_fail(...); }  // ❌ repeat twice!
};
if len == 1 {} else { __assert_fail(...); }
```

There is a bug!

### LINKED ISSUE #1509: About the mistranslation
**Original C Code:**

```c
int main(void) {
    assert(check_add());    // once 
    assert(check_sub());    // once
    return 0;
}
```

**C2rust Output:**

```rust
unsafe fn main_0() -> core::ffi::c_int {
    // first
    if check_add() {} else {
        __assert_fail(...);
    }
    
    // 🔴 second !!!
    'c_1569: {
        if check_add() {} else {
            __assert_fail(...);
        }
    };
    
    // first
    if check_sub() {} else {
        __assert_fail(...);
    }
    
    // 🔴 second !!!
    'c_1529: {
        if check_sub() {} else {
            __assert_fail(...);
        }
    };
    
    return 0 as core::ffi::c_int;
}
```

### PR DESCRIPTION
**Pull request by ahomescu**
* Fixes #1507.
* Fixes #1509.

### CODE REVIEW

File: tests/unit/misc/src/call_only_once.c
Comment (kkysen) [inline tests/unit/misc/src/call_only_once.c:1]: Can we also just have a snapshot test? It should be easy to see the translation of the assert.

**Comment by ahomescu** [comment]
@kkysen What are the steps for updating the macos snapshots for people running Linux?

File: c2rust-transpile/tests/snapshots/snapshots__transpile-linux@call_only_once.c.snap
Comment (kkysen) [inline c2rust-transpile/tests/snapshots/snapshots__transpile-linux@call_only_once.c.snap:1]: When we were transpiling dav1d, `assert(condition)`s would become a simple `if !condition { panic!(); }`.  What happened to that?  Did we change something, or did libc/clang change something?

Comment (ahomescu) [reply c2rust-transpile/tests/snapshots/snapshots__transpile-linux@call_only_once.c.snap:1]:
```rust
    if !(::core::mem::size_of::<Dav1dMemPoolBuffer>() as libc::c_ulong
        <= 64 as libc::c_int as libc::c_ulong)
    {
        unreachable!();
    }
```
This is what I found in rav1d for one `assert` call. I have no idea why it has `unreachable!` instead of `__assert_fail`.

Comment (ahomescu) [reply c2rust-transpile/tests/snapshots/snapshots__transpile-linux@call_only_once.c.snap:1]: https://github.com/memorysafety/rav1d/blob/main/src/include/common/attributes.h#L130 oh that's why!

Comment (kkysen) [reply c2rust-transpile/tests/snapshots/snapshots__transpile-linux@call_only_once.c.snap:1]: Ahh.  That's a shame.  That's a much easier translation to turn into `assert!`.

**Comment by ahomescu** [comment]
This passes the tests and has snapshots now, any more feedback?

File: c2rust-transpile/tests/snapshots.rs [hunk 1]
```diff
@@ -95,6 +95,9 @@ fn transpile(platform: Option<&str>, c_path: &Path) {
     let rs = fs::read_to_string(&rs_path).unwrap();
     let debug_expr = format!("cat {}", rs_path.display());
 
+    // Replace real paths with placeholders
+    let rs = rs.replace(cwd.to_str().unwrap(), "/c2rust-transpile");
```
Comment (kkysen) [inline c2rust-transpile/tests/snapshots.rs]:
```suggestion
    // Make absolute path strings relative
    // so that they compare the same no matter what the CWD is.
    let rs = rs.replace(cwd.to_str().unwrap(), ".");
```

I think it also make more sense to use `.` for replacing the CWD.

File: c2rust-transpile/src/translator/mod.rs [hunk 2]
```diff
@@ -4222,7 +4223,7 @@ impl<'c> Translation<'c> {
                 let result_id = substmt_ids[n - 1];
 
                 let name = format!("<stmt-expr_{:?}>", compound_stmt_id);
-                let lbl = cfg::Label::FromC(compound_stmt_id, None);
+                let lbl = cfg::Label::FromC(compound_stmt_id, Some(Rc::from("c2rust_stmt_expr")));
```
Comment (kkysen) [inline c2rust-transpile/src/translator/mod.rs]: Should we use `.pick_name`/`.pick_name_in_scope` for this?

File: c2rust-transpile/src/translator/mod.rs [hunk 3]
```diff
@@ -4265,10 +4269,19 @@ impl<'c> Translation<'c> {
...
-                Ok(WithStmts::new(stmts, val))
+                if ctx.is_unused() {
+                    Ok(WithStmts::new(
+                        vec![mk().semi_stmt(val)],
+                        self.panic_or_err(
+                            "Compound statement expression is not supposed to be used",
+                        ),
+                    ))
+                } else {
+                    Ok(WithStmts::new(vec![], val))
```
Comment (kkysen) [inline c2rust-transpile/src/translator/mod.rs]:
```suggestion
                    Ok(WithStmts::new_val(val))
```

File: c2rust-transpile/src/translator/mod.rs [hunk 4]
```diff
@@ -4243,20 +4244,23 @@ impl<'c> Translation<'c> {
...
+                                    self.panic_or_err(
+                                        "Compound statement expression is not supposed to be used",
+                                    ),
+                                ));
                             } else {
-                                Vec::new()
-                            };
-
-                            return Ok(WithStmts::new(stmts, val));
+                                return Ok(WithStmts::new(vec![], val));
```
Comment (kkysen) [inline c2rust-transpile/src/translator/mod.rs]:
```suggestion
                                return Ok(WithStmts::new_val(val));
```

File: c2rust-transpile/src/translator/mod.rs [hunk 5]
```diff
@@ -4265,10 +4269,19 @@ impl<'c> Translation<'c> {
...
+                if ctx.is_unused() {
+                    Ok(WithStmts::new(
+                        vec![mk().semi_stmt(val)],
+                        self.panic_or_err(
+                            "Compound statement expression is not supposed to be used",
+                        ),
+                    ))
+                } else {
+                    Ok(WithStmts::new(vec![], val))
+                }
```
Comment (kkysen) [inline c2rust-transpile/src/translator/mod.rs]:
```suggestion
                self.convert_side_effects_expr(
                    ctx,
                    WithStmts::new_val(val),
                    "Compound statement expression is not supposed to be used",
                )
```

File: c2rust-transpile/src/translator/mod.rs [hunk 6]
```diff
@@ -4243,20 +4244,23 @@ impl<'c> Translation<'c> {
...
                             let val = mk().paren_expr(block);
-                            let stmts = if ctx.is_unused() {
-                                vec![mk().semi_stmt(val.clone())]
+                            if ctx.is_unused() {
+                                return Ok(WithStmts::new(
+                                    vec![mk().semi_stmt(val)],
+                                    self.panic_or_err(
+                                        "Compound statement expression is not supposed to be used",
+                                    ),
+                                ));
```
Comment (kkysen) [inline c2rust-transpile/src/translator/mod.rs]:
```suggestion
                            return self.convert_side_effects_expr(
                                ctx,
                                WithStmts::new_val(val),
                                "Compound statement expression is not supposed to be used",
                            );
```

File: c2rust-transpile/src/translator/operators.rs [hunk 7]
```diff
@@ -931,17 +931,24 @@ impl<'c> Translation<'c> {
 
         // Some unused unary operators (`-foo()`) may have side effects, so we need
         // to add them to stmts when name is not increment/decrement operator.
+        //
+        // `Extension` is another exception since it's a no-op around the inner expression.
```
Comment (kkysen) [inline c2rust-transpile/src/translator/operators.rs]:
```suggestion
        // `UnOp::Extension` (`__extension__`) is another exception since it's a no-op around the inner expression.
```

File: c2rust-transpile/src/translator/operators.rs [hunk 8]
```diff
@@ -931,17 +931,24 @@ impl<'c> Translation<'c> {
...
             )
         {
-            let v = unary.clone().into_value();
-            unary.add_stmt(mk().semi_stmt(v));
+            unary = unary.and_then(|v| {
+                TranslationResult::Ok(WithStmts::new(
+                    vec![mk().semi_stmt(v)],
+                    self.panic_or_err("Unary expression is not supposed to be used"),
+                ))
+            })?;
```
Comment (kkysen) [inline c2rust-transpile/src/translator/operators.rs]:
```suggestion
            unary = self.convert_side_effects_expr(
                ctx,
                unary,
                "Unary expression is not supposed to be used",
            )?;
```

You can also get rid of the `ctx.is_unused() &&` since `self.convert_side_effects_expr` checks that already.

File: c2rust-transpile/src/translator/operators.rs [hunk 9]
```diff
@@ -931,17 +931,24 @@ impl<'c> Translation<'c> {
...
+        // `Extension` is another exception since it's a no-op around the inner expression.
         if ctx.is_unused()
             && !matches!(
                 name,
                 c_ast::UnOp::PreDecrement
                     | c_ast::UnOp::PreIncrement
                     | c_ast::UnOp::PostDecrement
                     | c_ast::UnOp::PostIncrement
+                    | c_ast::UnOp::Extension
             )
```
Comment (kkysen) [inline c2rust-transpile/src/translator/operators.rs]: Moving this to a `fn UnOp::may_have_side_effects` (and some of the comments) would help clarity I think.

Comment (ahomescu) [reply c2rust-transpile/src/translator/operators.rs]: It seems excessive to move a single `if` statement into a separate function. We should split it once it's used in 2-3 different places.

Comment (kkysen) [reply c2rust-transpile/src/translator/operators.rs]: Perhaps.  I find it clearer when separate, but not a big deal.  This is fine.

**Review by kkysen — APPROVED** [review]
Ideally, we'd split the macos snapshot across the commits like is done for the linux snapshot now, but that's a big pain, and the tests should still pass for each commit on Linux now, so I think it's fine.
