### PR TITLE
transpile: Extend lifetime of compound literals whose address is taken

### LINKED ISSUE #1217: Incorrect Value Read from Struct Initialized with `PTHREAD_RWLOCK_INITIALIZER`
This bug arises when using a **compound literal** to initialize a `struct` containing a `pthread_rwlock_t`, and passing a pointer to that struct to a thread. While this is safe and valid in C, the Rust code generated by **C2Rust** mishandles the struct's **memory lifetime** or **layout**, resulting in corrupted field values at runtime.

This issue is **distinct from [#1216]**, which involves `PTHREAD_MUTEX_INITIALIZER` and leads to a runtime crash. In contrast, this bug causes **silent data corruption** without triggering a panic or assertion failure.

## Source C code:

```c
#include <pthread.h>
#include <stdio.h>

typedef struct {
    pthread_rwlock_t lock;
    int val;
} S;

void *reader(void *arg) {
    S *s = arg;
    pthread_rwlock_rdlock(&s->lock);
    printf("val: %d\n", s->val);
    pthread_rwlock_unlock(&s->lock);
    return NULL;
}

int main() {
    pthread_t t;
    S *s = (S[]){ { PTHREAD_RWLOCK_INITIALIZER, 42 } };
    pthread_create(&t, NULL, reader, s);
    pthread_join(t, NULL);
    return 0;
}
```

## C Output:

```
val: 42
```

<details>
<summary>Click to view translated Rust code</summary>
```rust
#![allow(
    dead_code,
    mutable_transmutes,
    non_camel_case_types,
    non_snake_case,
    non_upper_case_globals,
    unused_assignments,
    unused_mut
)]
use ::transpiled_code::*;
extern "C" {
    fn pthread_create(
        __newthread: *mut pthread_t,
        __attr: *const pthread_attr_t,
        __start_routine: Option::<
            unsafe extern "C" fn(*mut libc::c_void) -> *mut libc::c_void,
        >,
        __arg: *mut libc::c_void,
    ) -> libc::c_int;
    fn pthread_join(
        __th: pthread_t,
        __thread_return: *mut *mut libc::c_void,
    ) -> libc::c_int;
    fn pthread_rwlock_rdlock(__rwlock: *mut pthread_rwlock_t) -> libc::c_int;
    fn pthread_rwlock_unlock(__rwlock: *mut pthread_rwlock_t) -> libc::c_int;
    fn printf(_: *const libc::c_char, _: ...) -> libc::c_int;
}
#[derive(Copy, Clone)]
#[repr(C)]
pub struct __pthread_rwlock_arch_t {
    pub __readers: libc::c_uint,
    pub __writers: libc::c_uint,
    pub __wrphase_futex: libc::c_uint,
    pub __writers_futex: libc::c_uint,
    pub __pad3: libc::c_uint,
    pub __pad4: libc::c_uint,
    pub __cur_writer: libc::c_int,
    pub __shared: libc::c_int,
    pub __rwelision: libc::c_schar,
    pub __pad1: [libc::c_uchar; 7],
    pub __pad2: libc::c_ulong,
    pub __flags: libc::c_uint,
}
pub type pthread_t = libc::c_ulong;
#[derive(Copy, Clone)]
#[repr(C)]
pub union pthread_attr_t {
    pub __size: [libc::c_char; 56],
    pub __align: libc::c_long,
}
#[derive(Copy, Clone)]
#[repr(C)]
pub union pthread_rwlock_t {
    pub __data: __pthread_rwlock_arch_t,
    pub __size: [libc::c_char; 56],
    pub __align: libc::c_long,
}
pub type C2RustUnnamed = libc::c_uint;
pub const PTHREAD_RWLOCK_DEFAULT_NP: C2RustUnnamed = 0;
pub const PTHREAD_RWLOCK_PREFER_WRITER_NONRECURSIVE_NP: C2RustUnnamed = 2;
pub const PTHREAD_RWLOCK_PREFER_WRITER_NP: C2RustUnnamed = 1;
pub const PTHREAD_RWLOCK_PREFER_READER_NP: C2RustUnnamed = 0;
#[derive(Copy, Clone)]
#[repr(C)]
pub struct S {
    pub lock: pthread_rwlock_t,
    pub val: libc::c_int,
}
#[no_mangle]
pub unsafe extern "C" fn reader(mut arg: *mut libc::c_void) -> *mut libc::c_void {
    let mut s: *mut S = arg as *mut S;
    pthread_rwlock_rdlock(&mut (*s).lock);
    printf(b"val: %d\n\0" as *const u8 as *const libc::c_char, (*s).val);
    pthread_rwlock_unlock(&mut (*s).lock);
    return 0 as *mut libc::c_void;
}
unsafe fn main_0() -> libc::c_int {
    let mut t: pthread_t = 0;
    let mut s: *mut S = [
        {
            let mut init = S {
                lock: pthread_rwlock_t {
                    __data: {
                        let mut init = __pthread_rwlock_arch_t {
                            __readers: 0 as libc::c_int as libc::c_uint,
                            __writers: 0 as libc::c_int as libc::c_uint,
                            __wrphase_futex: 0 as libc::c_int as libc::c_uint,
                            __writers_futex: 0 as libc::c_int as libc::c_uint,
                            __pad3: 0 as libc::c_int as libc::c_uint,
                            __pad4: 0 as libc::c_int as libc::c_uint,
                            __cur_writer: 0 as libc::c_int,
                            __shared: 0 as libc::c_int,
                            __rwelision: 0 as libc::c_int as libc::c_schar,
                            __pad1: [
                                0 as libc::c_int as libc::c_uchar,
                                0 as libc::c_int as libc::c_uchar,
                                0 as libc::c_int as libc::c_uchar,
                                0 as libc::c_int as libc::c_uchar,
                                0 as libc::c_int as libc::c_uchar,
                                0 as libc::c_int as libc::c_uchar,
                                0 as libc::c_int as libc::c_uchar,
                            ],
                            __pad2: 0 as libc::c_int as libc::c_ulong,
                            __flags: PTHREAD_RWLOCK_DEFAULT_NP as libc::c_int
                                as libc::c_uint,
                        };
                        init
                    },
                },
                val: 42 as libc::c_int,
            };
            init
        },
    ]
        .as_mut_ptr();
    pthread_create(
        &mut t,
        0 as *const pthread_attr_t,
        Some(reader as unsafe extern "C" fn(*mut libc::c_void) -> *mut libc::c_void),
        s as *mut libc::c_void,
    );
    pthread_join(t, 0 as *mut *mut libc::c_void);
    return 0 as libc::c_int;
}
pub fn main() {
    unsafe { ::std::process::exit(main_0() as i32) }
}
```
</details>

## Translated Rust Output:

Rust code prints incorrect value (e.g., `val: 0`) or worse — leads to undefined behavior.

```
val: 0
```

## Root Cause
C2Rust does not promote the temporary to a valid heap-allocated or static location. As a result, the memory becomes invalid by the time the thread accesses it.

### PR DESCRIPTION
**Pull request by Rua**
- Fixes #1217.

I've only looked at fixing it in function context, as it's not possible to add statements to static initializers ("Expected no side-effects in static initializer" panic). But I'm not sure if the issue exists for statics anyway, because Rust is forced to extend the lifetime of the temporary to static in such a context.

There is also an issue with how this line compiles in the snapshot test:
```c
char *static_char_ptr = (char[]) { "hello" };
```

It gets translated into an array in which the first element is the translated string, and then five zero integer literals. That's clearly broken and doesn't compile in Rust, so I commented out that line. Since my fix doesn't change how statics are handled, I believe that's an existing bug in c2rust that needs its own fix.

### CODE REVIEW

File: c2rust-transpile/tests/snapshots/compound_literals.c [hunk 1]
```diff
@@ -0,0 +1,11 @@
+int static_single_int = (int) { 42 };
+int *static_single_int_ptr = &((int) { 42 });
+int *static_int_array_ptr = (int[]) { 42, 9001 };
+//char *static_char_ptr = (char[]) { "hello" };
```
Comment (kkysen) [inline c2rust-transpile/tests/snapshots/compound_literals.c]: Can you add some of this explanation inline here?

> There is also an issue with how this line compiles in the snapshot test:
> ```c
> char *static_char_ptr = (char[]) { "hello" };
> ```
> 
> It gets translated into an array in which the first element is the translated string, and then five zero integer literals. That's clearly broken and doesn't compile in Rust, so I commented out that line. Since my fix doesn't change how statics are handled, I believe that's an existing bug in c2rust that needs its own fix.

File: c2rust-transpile/tests/snapshots/compound_literals.c
Comment (kkysen) [inline c2rust-transpile/tests/snapshots/compound_literals.c:1]: Can you add this snapshot in a separate commit so that there's a commit with its diff from the fixes you made?  Thanks!

Comment (kkysen) [reply c2rust-transpile/tests/snapshots/compound_literals.c:1]: I did this in 14713ae.

File: c2rust-transpile/src/translator/mod.rs [hunk 2]
```diff
@@ -4070,7 +4072,41 @@ impl<'c> Translation<'c> {
 
             Paren(_, val) => self.convert_expr(ctx, val, override_ty),
 
-            CompoundLiteral(_, val) => self.convert_expr(ctx, val, override_ty),
+            CompoundLiteral(qty, val) => {
+                let val = self.convert_expr(ctx, val, override_ty)?;
+
+                if !ctx.needs_address() || ctx.is_static {
```
Comment (kkysen) [inline c2rust-transpile/src/translator/mod.rs]:
```suggestion
                if !ctx.needs_address() || ctx.is_static {
                    // Statics have their intermediates' lifetimes extended.
```

File: c2rust-transpile/src/translator/mod.rs [hunk 3]
```diff
@@ -4070,7 +4072,41 @@ impl<'c> Translation<'c> {
...
+                    return Ok(val);
+                }
+
+                // C compound literals are lvalues, but equivalent Rust expressions generally
+                // are not. So if an address is needed, store it in an intermediate variable
+                // first.
```
Comment (kkysen) [inline c2rust-transpile/src/translator/mod.rs]: nit:

```suggestion
                // C compound literals are lvalues, but equivalent Rust expressions generally are not.
                // So if an address is needed, store it in an intermediate variable first.
```

**Comment by Rua** [comment]
I added extra tests to ensure that compound literals in macros don't undergo the same treatment as normal. Because they can be borrowed as statics, same as in #1379. However, I notice that the macro isn't used in the `macro_int_array_ptr` and `macro_char_array_ptr` cases, it's expanded to its definition and then given a fresh variable. Any idea why the macro is bypassed here?

File: c2rust-transpile/src/translator/mod.rs [hunk 4]
```diff
@@ -4070,7 +4072,41 @@ impl<'c> Translation<'c> {
 
             Paren(_, val) => self.convert_expr(ctx, val, override_ty),
 
-            CompoundLiteral(_, val) => self.convert_expr(ctx, val, override_ty),
+            CompoundLiteral(qty, val) => {
+                let val = self.convert_expr(ctx, val, override_ty)?;
+
+                if !ctx.needs_address() || ctx.is_static {
+                    // Statics have their intermediates' lifetimes extended.
```
Comment (kkysen) [inline c2rust-transpile/src/translator/mod.rs]:
```suggestion
                if !ctx.needs_address() || ctx.is_static || ctx.is_const {
                    // Statics and consts have their intermediates' lifetimes extended.
```

File: c2rust-transpile/tests/snapshots/compound_literals.c [hunk 5]
```diff
@@ -0,0 +1,22 @@
+int static_single_int = (int) { 42 };
+int *static_single_int_ptr = &((int) { 42 });
+int *static_int_array_ptr = (int[]) { 42, 9001 };
+// Currently generates broken Rust code, see
+// https://github.com/immunant/c2rust/issues/1410
+//char *static_char_array_ptr = (char[]) { "hello" };
+
+#define SINGLE_INT ((int) { 42 })
```
Comment (kkysen) [inline c2rust-transpile/tests/snapshots/compound_literals.c:11]: Can you move the macros to the test commit? Or a new commit in between.

Comment (kkysen) [reply c2rust-transpile/tests/snapshots/compound_literals.c:11]: I think you added the fresh changes to the original test commit, too.

**Comment by Rua** [comment]
This should be ready to go now.

**Review by kkysen — APPROVED** [review]
One of the snapshot lines was off in the first commit, but I fixed it, so this LGTM now.  Thanks again!
