### PR TITLE
Append `Metadata` to metadata file using a file lock

### LINKED ISSUE #586: `rustc_wrapper` is invoked twice during dynamic instrumentation
This causes the runtime to get finalized twice. The first time this occurs, it's during the collection of instrumentation points which causes the built-up set of `MirLocs` to get drained prematurely. This causes crashes when building the pointer derivation graph because of out-of-index access when attempting to process generated lighttpd events.

This issue needs #582 to reproduce, to get past #570.

### PR DESCRIPTION
**Pull request by kkysen**
Fixes #586.

This uses [`fs2`](https://docs.rs/fs2) file locking to append serialized `Metadata`s to the metadata file without race conditions.  Thanks for the suggestion, @ahomescu!

I'm unsure how to test for any race conditions, though.

### CODE REVIEW

File: dynamic_instrumentation/src/instrument.rs [hunk 1]
```diff
@@ -62,14 +65,22 @@ impl Instrumenter {
...
-        fs_err::write(metadata_file_path, &bytes).context("Could not open metadata file")?;
+        let mut file = OpenOptions::new()
+            .append(true)
+            .write(true)
+            .open(metadata_path)
+            .context("Could not open metadata file")?;
+        file.file().lock_exclusive()?;
+        let e = file.write_all(&bytes);
+        file.file().unlock()?;
+        e?;
```
Comment (kkysen) [inline dynamic_instrumentation/src/instrument.rs:83]: I wasn't sure how exactly to do this.  Am I correct in not returning the error until after unlocking the file so that we don't leave the file locked if there is a write error?  And is there a reason there's not a lock guard or something similar returned from locking?

Comment (aneksteind) [reply dynamic_instrumentation/src/instrument.rs:83]: I looks right to me to unlock before returning the error. I'd be curious if `write_all` could panic even though it returns a result. My guess about the locking guard is to match what the underlying sys crates are doing.

**Review by aneksteind — APPROVED** [review]

File: dynamic_instrumentation/src/instrument.rs (hunk 1 above)
Comment (kkysen) [reply dynamic_instrumentation/src/instrument.rs:83]: `write_all` shouldn't panic unless something is seriously wrong with the `write` syscall.

**Review by rinon — APPROVED** [review]
