### PR TITLE
transpile: Factor out common function for address-of and array-decay

### LINKED ISSUE #1238: `(void*)array` Cast Still Emits Invalid `*mut _` Despite Fix for Scalar-to-void* Casts (Related to #1077)
While issue [#1077](https://github.com/immunant/c2rust/issues/1077) has been resolved — allowing safe casts `(bool to void*)` like `void* x = (void*)b;` to correctly emit Rust code — the related pattern of `casting arrays to void*` still triggers incorrect output in the translated Rust. Rust error code is also different here.

## C code

```c
int array[10];
void* ptr = (void*)array;

int main() {
    return 0;
}
```

## Translated Rust code:

```rust
#[no_mangle]
pub static mut array: [libc::c_int; 10] = [0; 10];
#[no_mangle]
pub static mut ptr: *mut libc::c_void = unsafe {
    array.as_ptr() as *mut _ as *mut libc::c_void
};
```

## Rust build error:

```text
error[E0641]: cannot cast to a pointer of an unknown kind
  --> src/runner.rs:15:23
   |
15 |     array.as_ptr() as *mut _ as *mut libc::c_void
   |                       ^^^^^^ needs more type information
   |
   = note: the type information given here is insufficient to check whether the pointer cast is valid

For more information about this error, try `rustc --explain E0641`.
```

### LINKED ISSUE #1240: Compound Literal Assigned to `volatile int*` Triggers Invalid Pointer Cast in Transpiled Rust
## Description

C2Rust generates invalid Rust code when a `volatile int*` is initialized using a compound literal. The transpiler emits a pointer cast involving `*mut _`, which leads to a compilation failure in Rust due to an ambiguous pointer type.

This issue **does not occur** when the same code uses `int*` or `const int*` instead.

## C code:

```c
volatile int *vs = { (int[]){1, 2, 3} }; 
```

## Translated Rust Code:

```rust
pub static mut vs: *mut libc::c_int = [1, 2, 3].as_ptr() as *mut _ as *mut libc::c_int;
unsafe fn main_0() -> libc::c_int {
    return 0 as libc::c_int;
}
```

## Cargo build failure:

```text
error[E0641]: cannot cast to a pointer of an unknown kind
  --> src/runner.rs:12:61
   |
12 | pub static mut vs: *mut libc::c_int = [1, 2, 3].as_ptr() as *mut _ as *mut libc::c_int;
   |                                                             ^^^^^^ needs more type information
   |
   = note: the type information given here is insufficient to check whether the pointer cast is valid

For more information about this error, try `rustc --explain E0641`.
```

### PR DESCRIPTION
**Pull request by Rua**
Depends on #1478.

- Fixes #1240.
- Fixes #1238.

This combines handling of the address-of and array-decay cast into a common function.

In the current code, this check for whether the created pointer type has a different pointee than the actual desired pointee type is only applied to array-to-pointer decays but not address-of. I left it that way, but perhaps it's also good to have it for address-of?
https://github.com/immunant/c2rust/blob/bbeb6de0e6d779a98c45947c7edc4ae77cb55ae4/c2rust-transpile/src/translator/mod.rs#L4837-L4843

### CODE REVIEW

**Comment by Rua** [comment]
Could this PR (and #1478) be reviewed soon? It's becoming rather a blocker for other things at the moment.

**Comment by ahomescu** [comment]
#1478 seems fine to me, I approved it. For this one, you might need to add some reviewers (I'll ask tomorrow if anyone wants to volunteer).

**Comment by Rua** [comment]
> For this one, you might need to add some reviewers (I'll ask tomorrow if anyone wants to volunteer).

I don't think regular users can add/request reviewers on this repo? Unless I'm missing something.

File: c2rust-transpile/src/translator/mod.rs [hunk 1]
```diff
@@ -3085,13 +3093,8 @@ impl<'c> Translation<'c> {
...
         if is_static && !pointee.qualifiers.is_const {
-            let mut qtype = pointee;
-            qtype.qualifiers.is_const = true;
-            let ty_ = self
-                .type_converter
-                .borrow_mut()
-                .convert_pointer(&self.ast_context, qtype)?;
-            zero = mk().cast_expr(zero, ty_);
+            let ty_ = self.convert_pointee_type(pointee.ctype)?;
+            zero = mk().cast_expr(zero, mk().ptr_ty(ty_));
```
Comment (fw-immunant) [inline c2rust-transpile/src/translator/mod.rs:3097]: Should this still be translating the pointee type with `is_const` set to `true`?

File: c2rust-transpile/src/translator/operators.rs [hunk 2]
```diff
@@ -1009,13 +1009,8 @@ impl<'c> Translation<'c> {
...
                             if let Mutability::Mutable = mutbl {
-                                let mut qtype = pointee_ty;
-                                qtype.qualifiers.is_const = true;
-                                let ty_ = self
-                                    .type_converter
-                                    .borrow_mut()
-                                    .convert_pointer(&self.ast_context, qtype)?;
-                                addr_of_arg = mk().cast_expr(addr_of_arg, ty_);
+                                let ty_ = self.convert_pointee_type(pointee_ty.ctype)?;
+                                addr_of_arg = mk().cast_expr(addr_of_arg, mk().ptr_ty(ty_));
```
Comment (fw-immunant) [inline c2rust-transpile/src/translator/operators.rs]: Same concern as the other hunk: should this still be translating the pointee type with `is_const` set to `true`?

File: c2rust-transpile/src/translator/mod.rs [hunk 3]
```diff
@@ -4708,84 +4708,12 @@ impl<'c> Translation<'c> {
...
-                            // mutable pointer as we do here:
-                            if ctx.is_static && !is_const {
-                                return Ok(call.map(|val| {
-                                    let inferred_type = mk().infer_ty();
-                                    let ptr_type = mk().mutbl().ptr_ty(inferred_type);
-                                    mk().cast_expr(val, ptr_type)
-                                }));
-                            }
-
-                            Ok(call)
```
Comment (fw-immunant) [inline c2rust-transpile/src/translator/mod.rs:4781]: What happened to this hunk in the factoring? Is there a reason it's no longer necessary? It seems like `infer_ty` is no longer emitted, based on the change in snapshot output.

Ideally this kind of non-obvious change during a refactor would be noted in the commit message.

File: c2rust-transpile/tests/snapshots/snapshots__transpile@macros.c.snap [hunk 4]
```diff
@@ -370,7 +370,7 @@ pub static mut fns: fn_ptrs = {
     init
 };
 #[no_mangle]
-pub static mut p: *const fn_ptrs = unsafe { &fns as *const fn_ptrs };
```
Comment (fw-immunant) [inline c2rust-transpile/tests/snapshots/snapshots__transpile@macros.c.snap:373]: It's strange that this is unsafe, but that isn't changed by these commits. Just a note to self to look into this.

File: c2rust-transpile/src/translator/mod.rs (hunk 1 above)
Comment (Rua) [reply c2rust-transpile/src/translator/mod.rs:3097]: I think that question properly applies to the changes made in #1478? This PR depends on that other PR first, but I split them because #1479 also needs those changes.

File: c2rust-transpile/src/translator/mod.rs (hunk 3 above)
Comment (Rua) [reply c2rust-transpile/src/translator/mod.rs:4781]: The intermediate cast that's inserted there is now handled by setting `ref_cast_pointee_ty` if `needs_cast` is `true`:
https://github.com/immunant/c2rust/blob/5a55ba952ee03e18a01f4ec86477864de5241f82/c2rust-transpile/src/translator/mod.rs#L4950-L4958

The logic is that an intermediate cast is required if a final cast is also being done, because you can't cast a reference to just any pointer type; only to the corresponding pointer type (or to its element in the case of arrays). I agree that it's not exactly obvious that it's doing the same thing, the refactoring changes it around quite a bit.

I did remove `infer_ty` because that was the source of the problem in the two issues that this PR fixes (listed in the first post). So now there is always an explicit type given, which is generated by `convert_pointee_type`.

EDIT: I've added an extra line to the commit message now.

File: c2rust-transpile/tests/snapshots/snapshots__transpile@macros.c.snap (hunk 4 above)
Comment (Rua) [reply c2rust-transpile/tests/snapshots/snapshots__transpile@macros.c.snap:373]: It's borrowing a `static mut`, so I think it needs to be?

File: c2rust-transpile/src/translator/mod.rs (hunk 3 above)
Comment (fw-immunant) [reply c2rust-transpile/src/translator/mod.rs:4781]: Ok, thanks for the clarification.

File: c2rust-transpile/tests/snapshots/snapshots__transpile@macros.c.snap (hunk 4 above)
Comment (fw-immunant) [reply c2rust-transpile/tests/snapshots/snapshots__transpile@macros.c.snap:373]: Ah, I didn't realize that it was `static mut`.

File: c2rust-transpile/src/translator/mod.rs (hunk 1 above)
Comment (fw-immunant) [reply c2rust-transpile/src/translator/mod.rs:3097]: It does indeed. I'll move this comment over there.

**Comment by fw-immunant** [comment]
Modulo comments on #1478, which this includes as its first commit, LGTM.
