### PR TITLE
transpile: support anonymous `struct`/`union`/`enum`s within `struct`s and `union`s

### LINKED ISSUE #1233: C2Rust Crashes on Anonymous Enum Without Field in Anonymous Union Inside Struct
C2Rust crashes when transpiling valid C code that includes an anonymous enum inside an anonymous union within a `struct`, due to the lack of a field name for the `enum`. While this is standard-compliant C (accepted by GCC and Clang), C2Rust panics with a missing key lookup in its AST processing.

## C code:

```c
struct temp {
    union {
        enum {
            VALUE_1,
            VALUE_2
        };
        int int_value;
    } u;
};

int main() {
    struct temp b;
    b.u.int_value = VALUE_2;
    return 0;
}
```

## C2Rust error:

```text
$c2rust-transpile compile_commands.json -e -o transpiled_code --binary runner
Transpiling runner.c
thread 'main' panicked at c2rust-transpile/src/c_ast/mod.rs:653:57:
no entry found for key
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

c2rust version: `C2Rust 0.20.0`

### PR DESCRIPTION
**Pull request by bungcip**
* Fixes #1233.

`RecordDecl` can have anonymous struct or enum as children so we must collect them so they can have parent in `TypedAstContext`.

### CODE REVIEW

File: c2rust-ast-exporter/src/AstExporter.cpp [hunk 1]
```diff
@@ -2098,9 +2098,16 @@ class TranslateASTVisitor final
...
-                childIds.push_back(x->getCanonicalDecl());
+            for (auto x : def->decls()) {
+                auto kind = x->getKind();
+                // Note: We skip IndirectFieldDecl
+                if(kind == Decl::Kind::Field 
+                    || kind == Decl::Kind::Enum 
+                    || kind == Decl::Kind::Record) {
+                    childIds.push_back(x->getCanonicalDecl());
+                }
             }
```
Comment (kkysen) [inline c2rust-ast-exporter/src/AstExporter.cpp]:
```suggestion
            for (auto decl : def->decls()) {
                auto kind = decl->getKind();
                // Note: We skip `Decl::Kind::IndirectField`.
                if (kind == Decl::Kind::Field 
                    || kind == Decl::Kind::Enum 
                    || kind == Decl::Kind::Record) {
                    childIds.push_back(decl->getCanonicalDecl());
                }
            }
```

File: c2rust-transpile/src/c_ast/conversion.rs [hunk 2]
```diff
@@ -519,6 +519,36 @@ impl ConversionContext {
         self.typed_context.target = untyped_context.target.clone();
     }
 
+    /// visit children node in RecordDecl (Struct/Union) and collect FieldDecl node id
```
Comment (kkysen) [inline c2rust-transpile/src/c_ast/conversion.rs]:
```suggestion
    /// Visit child nodes of a `RecordDecl` (`struct` or `union`) and collect `FieldDecl` node IDs.
```

File: c2rust-transpile/tests/snapshots/records.c [hunk 3]
```diff
@@ -0,0 +1,75 @@
...
+
+void union_declaration()
+{
+    int value = VALUE4;
+    union AnonEnumInUnion a;
+    union AnonStructInUnion b;
+    b.some_number = 99;
+    union NestedStructInUnion c;
+    struct UnionInsider d;
+}
```
Comment (kkysen) [inline c2rust-transpile/tests/snapshots/records.c]:
```suggestion
}

```

File: c2rust-transpile/tests/snapshots/records.c [hunk 4]
```diff
@@ -0,0 +1,75 @@
+// record (struct/union) declaration
+
+struct AnonEnumInStruct
+{
```
Comment (kkysen) [inline c2rust-transpile/tests/snapshots/records.c]:
```suggestion
struct AnonEnumInStruct {
```

Could you format things like this, here and the other places like this?  I think that's the style we generally use.

File: c2rust-transpile/src/c_ast/conversion.rs [hunk 5]
```diff
@@ -519,6 +519,36 @@ impl ConversionContext {
...
+    fn visit_record_children(
+        &mut self,
+        untyped_context: &AstContext,
+        node: &AstNode,
+        new_id: ImporterId,
+    ) -> Vec<CDeclId> {
```
Comment (kkysen) [inline c2rust-transpile/src/c_ast/conversion.rs]:
```suggestion
    ) -> impl Iterator<Item = CDeclId> {
```

File: c2rust-transpile/src/c_ast/conversion.rs [hunk 6]
```diff
@@ -519,6 +519,36 @@ impl ConversionContext {
...
+                let id = CDeclId(self.visit_node_type(decl, FIELD_DECL | ENUM_DECL | RECORD_DECL));
+                self.typed_context.parents.insert(id, CDeclId(new_id));
+
+                if decl_node.tag == ASTEntryTag::TagFieldDecl {
+                    Some(id)
+                } else {
+                    None
+                }
+            })
+            .collect()
```
Comment (kkysen) [inline c2rust-transpile/src/c_ast/conversion.rs]:
```suggestion
```

Comment (kkysen) [reply c2rust-transpile/src/c_ast/conversion.rs]: Can you move the `.collect()`s to the caller?

File: c2rust-transpile/src/c_ast/conversion.rs [hunk 7]
```diff
@@ -519,6 +519,36 @@ impl ConversionContext {
...
+        use self::node_types::*;
+
+        node.children
+            .iter()
+            .filter_map(|id| {
+                let decl = id.expect("Record decl not found");
+                let decl_node = untyped_context
+                    .ast_nodes
+                    .get(&decl)
+                    .expect("child node not found found");
```
Comment (kkysen) [inline c2rust-transpile/src/c_ast/conversion.rs]:
```suggestion
                    .expect("child node not found");
```

File: c2rust-transpile/tests/snapshots/records.c [hunk 8]
```diff
@@ -0,0 +1,75 @@
...
+    struct
+    {
+        int some_number;
+    };
+};
+
+struct NestedStructInStruct
+{
+    struct StructInsider
```
Comment (kkysen) [inline c2rust-transpile/tests/snapshots/records.c]:
```suggestion
    struct InsideStruct
```

File: c2rust-transpile/tests/snapshots/records.c [hunk 9]
```diff
@@ -0,0 +1,75 @@
...
+    struct
+    {
+        int some_number;
+    };
+    int a;
+};
+
+union NestedStructInUnion
+{
+    struct UnionInsider
```
Comment (kkysen) [inline c2rust-transpile/tests/snapshots/records.c]:
```suggestion
    struct InsideUnion
```

File: c2rust-transpile/src/c_ast/conversion.rs [hunk 10]
```diff
@@ -519,6 +519,36 @@ impl ConversionContext {
         self.typed_context.target = untyped_context.target.clone();
     }
 
+    /// visit children node in RecordDecl (Struct/Union) and collect FieldDecl node id
+    fn visit_record_children(
```
Comment (kkysen) [inline c2rust-transpile/src/c_ast/conversion.rs]: Preferably, if it's not too much work, it'd be nice to first have a refactor commit that just outlines the two calls into a `fn visit_record_fields`, and then have a separate commit that fixes the main issue.

File: c2rust-ast-exporter/src/AstExporter.cpp (hunk 1 above)
Comment (bungcip) [reply c2rust-ast-exporter/src/AstExporter.cpp]: done

File: c2rust-transpile/src/c_ast/conversion.rs (hunk 2 above)
Comment (bungcip) [reply c2rust-transpile/src/c_ast/conversion.rs]: done

File: c2rust-transpile/tests/snapshots/records.c (hunk 3 above)
Comment (bungcip) [reply c2rust-transpile/tests/snapshots/records.c]: done

File: c2rust-transpile/tests/snapshots/records.c (hunk 4 above)
Comment (bungcip) [reply c2rust-transpile/tests/snapshots/records.c]: done

Comment (bungcip) [reply c2rust-transpile/tests/snapshots/records.c]: done

File: c2rust-transpile/src/c_ast/conversion.rs (hunk 7 above)
Comment (bungcip) [reply c2rust-transpile/src/c_ast/conversion.rs]: done

File: c2rust-transpile/tests/snapshots/records.c (hunk 9 above)
Comment (bungcip) [reply c2rust-transpile/tests/snapshots/records.c]: done

File: c2rust-transpile/tests/snapshots/records.c (hunk 8 above)
Comment (bungcip) [reply c2rust-transpile/tests/snapshots/records.c]: done

File: c2rust-transpile/src/c_ast/conversion.rs (hunk 10 above)
Comment (bungcip) [reply c2rust-transpile/src/c_ast/conversion.rs]: ok, I already split the PR to 2 commits:
1) first commit to refactor visiting record fields to `visit_record_children`
2) second commit to fix the main issue

File: c2rust-transpile/src/c_ast/conversion.rs (hunk 5 above)
Comment (bungcip) [reply c2rust-transpile/src/c_ast/conversion.rs]: done

File: c2rust-transpile/src/c_ast/conversion.rs (hunk 6 above)
Comment (bungcip) [reply c2rust-transpile/src/c_ast/conversion.rs]: done

**Comment by bungcip** [comment]
hi @kkysen, sorry for late response. can you review this PR again?

**Review by kkysen — APPROVED** [review]
Thanks! All LGTM now.
