### PR TITLE
properly handle `ASTEntryTag::TagStaticAssertDecl` conversion

### LINKED ISSUE #1332: Error while using c2rust - thread 'main' panicked at 'no entry found for key'
I built c2rust from the master per the suggestion in #1329.

Did I do something wrong or is this a problem in c2rust?

**Here is what I did:**
1. I cloned the [fsearch](https://github.com/cboxdoerfer/fsearch) repo: https://github.com/cboxdoerfer/fsearch
2. I created the _compile_commands.json_ using the following commands:
`meson setup builddir`
`ninja -C builddir`
3. Then from the root of the project I did: `RUST_BACKTRACE=1 c2rust transpile builddir/compile_commands.json`
4. This is the result:

> warning: Skipping duplicate compilation cmd for /opt/Projects/fsearch/builddir/src/ui_resources.c
> warning: Skipping duplicate compilation cmd for /opt/Projects/fsearch/builddir/src/icon_resources.c
> warning: Skipping duplicate compilation cmd for /opt/Projects/fsearch/builddir/src/ui_resources.c
> warning: Skipping duplicate compilation cmd for /opt/Projects/fsearch/builddir/src/icon_resources.c
> warning: Skipping duplicate compilation cmd for /opt/Projects/fsearch/builddir/src/ui_resources.c
> warning: Skipping duplicate compilation cmd for /opt/Projects/fsearch/builddir/src/icon_resources.c
> warning: Skipping duplicate compilation cmd for /opt/Projects/fsearch/builddir/src/ui_resources.c
> warning: Skipping duplicate compilation cmd for /opt/Projects/fsearch/builddir/src/icon_resources.c
> warning: Skipping duplicate compilation cmd for /opt/Projects/fsearch/builddir/src/ui_resources.c
> warning: Skipping duplicate compilation cmd for /opt/Projects/fsearch/builddir/src/icon_resources.c
> warning: Skipping duplicate compilation cmd for /opt/Projects/fsearch/builddir/src/ui_resources.c
> warning: Skipping duplicate compilation cmd for /opt/Projects/fsearch/builddir/src/icon_resources.c
> Transpiling ui_resources.c
> Transpiling icon_resources.c
> Transpiling fsearch.c
> thread 'main' panicked at 'no entry found for key', c2rust-transpile/src/c_ast/iterators.rs:341:69
> stack backtrace:
>    0: rust_begin_unwind
>              at /rustc/d394408fb38c4de61f765a3ed5189d2731a1da91/library/std/src/panicking.rs:584:5
>    1: core::panicking::panic_fmt
>              at /rustc/d394408fb38c4de61f765a3ed5189d2731a1da91/library/core/src/panicking.rs:142:14
>    2: core::panicking::panic_display
>              at /rustc/d394408fb38c4de61f765a3ed5189d2731a1da91/library/core/src/panicking.rs:72:5
>    3: core::panicking::panic_str
>              at /rustc/d394408fb38c4de61f765a3ed5189d2731a1da91/library/core/src/panicking.rs:56:5
>    4: core::option::expect_failed
>              at /rustc/d394408fb38c4de61f765a3ed5189d2731a1da91/library/core/src/option.rs:1874:5
>    5: c2rust_transpile::c_ast::iterators::immediate_children_all_types
>    6: c2rust_transpile::c_ast::iterators::NodeVisitor::visit_tree
>    7: c2rust_transpile::translator::comments::<impl c2rust_transpile::translator::Translation>::locate_comments
>    8: c2rust_transpile::translator::translate
>    9: c2rust_transpile::transpile_single
>   10: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
>   11: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
>   12: c2rust_transpile::transpile
>   13: c2rust_transpile::main
> note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

### PR DESCRIPTION
**Pull request by bungcip**
visit children nodes in StaticAssertDecl, so all children exprs will be inserted in `ast_context.c_exprs`. without visiting it, we will get panic  'no entry found for key' when translator try to convert `_Static_assert`.

* Fixes #1332.

### CODE REVIEW

**Review by kkysen — COMMENTED** [review]
By the way, I don't think "fixing" is one of the closing keywords so I changed it to "fix".

**Comment by bungcip** [comment]
hi @kkysen, thanks for the correction, i am not native english speaker so sometimes my choice of word is litttle weird 😅

File: c2rust-transpile/src/c_ast/conversion.rs [hunk 1]
```diff
@@ -1261,7 +1261,11 @@ impl ConversionContext {
                 }
 
                 ASTEntryTag::TagStringLiteral if expected_ty & (EXPR | STMT) != 0 => {
-                    let ty_old = node.type_id.expect("Expected expression to have type");
+                    // https://github.com/immunant/c2rust/issues/1332
+                    // string literals from assert message like this expression
+                    // _Static_assert(1, "message")
+                    //  don't have type. so we give it zero for now
```
Comment (kkysen) [inline c2rust-transpile/src/c_ast/conversion.rs]: What does 0 mean for a type ID?

Comment (kkysen) [inline c2rust-transpile/src/c_ast/conversion.rs]:
```suggestion
                    // See <https://github.com/immunant/c2rust/issues/1332>.
                    // String literals from `_Static_assert`s don't have a type,
                    // so we give it 0 for now because ...
```

Something like this with more of an explanation for what 0 means would be helpful.

**Review by kkysen — COMMENTED** [review]
The `TagStaticAssertDecl` changes LGTM (thanks!), but I'm confused about what the 0 means for `TagStringLiteral` and what visiting a type ID of 0 means.  That said, I'm also not familiar with the code here, so I might be missing something, but more of an explanation in the comment would be very helpful.

File: c2rust-transpile/src/c_ast/conversion.rs (hunk 1 above)
Comment (bungcip) [reply c2rust-transpile/src/c_ast/conversion.rs]: I admit this is little hackish😅. I just used least likely used type id which not used by anything (zero). For now because we just skipping transpiling _static_assert, this is fine, but when someday we try to properly to convert `_Static_assert` to `assert!()` or `debug_assert()`, this code will causing panic when accessing the type. 
The right fix is i think we need to give ASTEntryTag::TagStringLiteral some dummy type from C++ side in `ast-exporter`, maybe tonight i will try to familiarize with CLang/LLVM API first

Comment (bungcip) [reply c2rust-transpile/src/c_ast/conversion.rs]: I changed the code so we don't need to use this hack. So `StaticAssertDecl` will only visit first parameter, for second parameter, because second parameter of assert is always string literal we just extract the string message and store it directly in CDeclKind::StaticAssert

Comment (bungcip) [reply c2rust-transpile/src/c_ast/conversion.rs]: see https://github.com/immunant/c2rust/pull/1342#discussion_r2307474959

**Comment by bungcip** [comment]
hi @kkysen, can review it again? I changed  the code so we don't change the invariant in StringLiteral

File: c2rust-transpile/tests/snapshots/static_assert.c [hunk 2]
```diff
@@ -0,0 +1,3 @@
+void static_assert() {
+    _Static_assert (1, "Expression evaluates to false");
```
Comment (kkysen) [inline c2rust-transpile/tests/snapshots/static_assert.c:3]:
```suggestion
    _Static_assert(0);
    _Static_assert(1, "Expression evaluates to false");
```

We should test the case without a message as well.

**Comment by kkysen** [comment]
> I changed the code so we don't change the invariant in StringLiteral

This looks good now.  I can merge it just with that test tweak.

**Comment by bungcip** [comment]
rebased and adding test case for static assert without message

**Review by kkysen — APPROVED** [review]
LGTM, thanks!
