### PR TITLE
Install `FileCheck` for older (`apt`-based) distros

### LINKED ISSUE #477: Catch more compile-time errors in CI
Right now in CI, we just test

```sh
cargo build
./scripts/test_translator.py tests/
```

We should test more:

```sh
cargo fmt --check
RUSTFLAGS='-D warnings' cargo clippy --tests --all --all-features # includes cargo build
RUSTDOCFLAGS='-D warnings' cargo doc --all-features --document-private-items
cargo test --all-features
./scripts/test_translator.py tests/
# immunant/c2rust-testsuite CI
```

Furthermore, we should run the external tests, `./scripts/test_translator.py tests/` and [`immunant/c2rust-testsuite`](https://github.com/immunant/c2rust-testsuite) CI inside of `cargo test`.  This not only simplifies testing workflows, but also hooks into external testing, such as crater runs.

I think we should definitely add these at least by the time we move CI to GitHub Actions instead of Azure Pipelines, but preferably earlier, as `cargo clippy` is almost passing (https://github.com/immunant/c2rust/issues/474), and once it is, I'd like to keep it that way.

### LINKED ISSUE #593: `cargo test -p c2rust-analyze` fails CI due to no `FileCheck`
On Ubuntu 18 and Debian 10, `FileCheck` is not installed by default with `llvm`, so `cargo test -p c2rust-analyze` fails.

We can either upgrade `llvm` versions on those distros (and stop supporting LLVM 6) or just install `llvm-${major}.${minor}-tools` on those old distros, which installs `FileCheck`.  I think the latter is preferable as otherwise, we have to fix the `provision_deb.sh` script to sometimes install `llvm` and sometimes `llvm-${version}`.  Furthermore, installing `llvm-${major}-tools` on newer distros is probably smarter to ensure `FileCheck` is always there.

The other problem is that `c2rust-analyze/tests/filecheck.rs` looks for `FileCheck` independently, and doesn't currently work for `FileCheck-6.0`.  Instead, we should match the `llvm-config` resolution in `c2rust-ast-exporter/build.rs` and then use `$(llvm-config --bindir)/FileCheck`, which is more reliable and always matches in behavior.

To do this, I want to move `find_llvm_config` to `rustc-private-link` or `build-utils` (whatever it's renamed to in https://github.com/immunant/c2rust/pull/591).

Blocked on:
* #641
* #618

### PR DESCRIPTION
**Pull request by kkysen**
- Fixes #593, along with the changes just merged in #767.

This installs `FileCheck` for older (`apt`-based) distros so that we can use `FileCheck` in testing without having to disable it anywhere.  Notably, we can use `FileCheck` for `c2rust-analyze` tests.

These older distros/default LLVM versions require the `llvm-${major}-tools` or `llvm-${major}.${minor}-tools` packages, while newer ones install `FileCheck` automatically, so this adds the installation of the older versions if `FileCheck` is not found in the expected location, `$(llvm-config --bindir)/FileCheck`, using the same `llvm-config` resolution used elsewhere.

This changes the docker builds, so we'll need a `./scripts/docker_build.sh push-all`.

This also adds an array of packages in the script, which makes adding to it easier, as well as allowing for inline comments (which don't work with `\` line continuation).

### CODE REVIEW

**Review by aneksteind — APPROVED** [review]

File: scripts/provision_deb.sh [hunk 1]
```diff
@@ -56,6 +56,16 @@ apt-get install -qq \
...
     zlib1g-dev
 
+if ! [[ -x "$(llvm-config --bindir)/FileCheck" ]]; then
+	IFS="." read -r major minor patch <<< "$(llvm-config --version)"
+    if [[ ${major} -gt 6 ]]; then
+        tools="llvm-${major}-tools"
+    else
+        tools="llvm-${major}.${minor}-tools"
+    fi
+    apt install "${tools}"
```
Comment (thedataking) [inline scripts/provision_deb.sh:66]: Why does this not use -qq like the other `apt install` invocation?

This would not have been a problem if you had re-used the existing `apt install` invocation. You could define a variable `packages` and simply add to that if `FileCheck` is not installed.

Also, would dropping support for LLVM 6 (I think that's safe to do by now) allow you to just add a static package name? If so, that would be better.

Side notes: 
- Can you remove the retry loop for `apt update -qq` in a separate commit? We don't need that anymore. I think I put it in but I don't think we run this script in CI anymore so it is confusing to not just `apt update -qq`.
- Do you need to update the GitHub Actions provisioning code too?

**Review by thedataking — CHANGES_REQUESTED** [review]
I'd like to know if dropping LLVM 6 support would simplify the provisioning change you are proposing.

File: scripts/provision_deb.sh (hunk 1 above)
Comment (thedataking) [reply scripts/provision_deb.sh:66]: This does not seem to work for `build_docker.sh debian:buster`. I see this on Donna:

```
The following additional packages will be installed:
  python-chardet python-pkg-resources python-pygments python-yaml
Suggested packages:
  python-setuptools python-pygments-doc ttf-bitstream-vera
The following NEW packages will be installed:
  llvm-7-tools python-chardet python-pkg-resources python-pygments python-yaml
0 upgraded, 5 newly installed, 0 to remove and 1 not upgraded.
Need to get 1225 kB of archives.
After this operation, 5753 kB of additional disk space will be used.
Do you want to continue? [Y/n] Abort.
The command '/bin/sh -c chmod +x /tmp/provision*.sh && /tmp/provision.sh' returned a non-zero code: 1
```

Comment (kkysen) [reply scripts/provision_deb.sh:66]: > Why does this not use -qq like the other `apt install` invocation?

Oops, I missed that.  By the way, is there a reason why things like `-qq` are used?  I usually have to turn them all off when I'm debugging anything.  Also, is there a reason `apt-get install` is used instead of `apt install`?

> This would not have been a problem if you had re-used the existing `apt install` invocation. You could define a variable `packages` and simply add to that if `FileCheck` is not installed.

I could do it that way instead.  I thought this way was more minimally invasive.

> Also, would dropping support for LLVM 6 (I think that's safe to do by now) allow you to just add a static package name? If so, that would be better.

We'd need to drop Ubuntu 18 and Debian 10 support, as it's the default LLVM version on those platforms and that's where the problem arises.

> * Can you remove the retry loop for `apt update -qq` in a separate commit? We don't need that anymore. I think I put it in but I don't think we run this script in CI anymore so it is confusing to not just `apt update -qq`.

Sure.

> * Do you need to update the GitHub Actions provisioning code too?

I wasn't sure if that needed to be.  The package list there is a bit different, so I wasn't sure if I'm supposed to add to both.  I don't think the `c2rust-testsuite` action we have runs `cargo test` and thus doesn't need `FileCheck`.

Comment (kkysen) [reply scripts/provision_deb.sh:66]: > This does not seem to work for `build_docker.sh debian:buster`. I see this on `donna`:
> 
> ```
> The following additional packages will be installed:
>   python-chardet python-pkg-resources python-pygments python-yaml
> Suggested packages:
>   python-setuptools python-pygments-doc ttf-bitstream-vera
> The following NEW packages will be installed:
>   llvm-7-tools python-chardet python-pkg-resources python-pygments python-yaml
> 0 upgraded, 5 newly installed, 0 to remove and 1 not upgraded.
> Need to get 1225 kB of archives.
> After this operation, 5753 kB of additional disk space will be used.
> Do you want to continue? [Y/n] Abort.
> The command '/bin/sh -c chmod +x /tmp/provision*.sh && /tmp/provision.sh' returned a non-zero code: 1
> ```

Oh, I thought I had tested building all of them.  Let me check again.

Comment (kkysen) [reply scripts/provision_deb.sh]: > You could define a variable `packages` and simply add to that if FileCheck is not installed.

Fixed in 44b4c0eb99177601df8429a908e48b36e0f27bec and 1e80811a474eb45bfdbdfad1142edf3047f9bc9f.

> Why does this not use -qq like the other apt install invocation?

> This would not have been a problem if you had re-used the existing apt install invocation.

Fixed in 1e80811a474eb45bfdbdfad1142edf3047f9bc9f.

> Can you remove the retry loop for apt update -qq in a separate commit? We don't need that anymore. I think I put it in but I don't think we run this script in CI anymore so it is confusing to not just apt update -qq.

I'll do that separately at some point.

Comment (kkysen) [reply scripts/provision_deb.sh]: @thedataking, I think it should be ready to go now.

I think doing it this way is simpler than dropping LLVM 6 and Ubuntu 18/Debian 10 support and making sure nothing breaks.  Making sure we don't break anything seems much more difficult.

> Can you remove the retry loop for `apt update -qq` in a separate commit? We don't need that anymore. I think I put it in but I don't think we run this script in CI anymore so it is confusing to not just `apt update -qq`.

This is done separately in #781.

**Comment by kkysen** [comment]
@thedataking said it looks better, so I'll merge now.

File: scripts/provision_deb.sh (hunk 1 above)
Comment (kkysen) [reply scripts/provision_deb.sh]: > You could define a variable `packages` and simply add to that if `FileCheck` is not installed.

I'm going to switch back to the previous way, as this logic needs `llvm-config`, and thus needs `llvm` to be installed first.  So I need separate `apt install` commands.
