### PR TITLE
transpile: fix out-of-range literals

### LINKED ISSUE #1435: Integer literal overflow in C causes Rust compilation error
C source code (from [LibmCS](https://gitlab.com/gtd-gmbh/libmcs/-/blob/1.2.0/libm/mathd/sqrtd.c?ref_type=tags#L63)):
```c
int32_t sign = 0x80000000U;
```
C2Rust 0.21.0 translates it to:
```rust
pub type int32_t = __int32_t;
pub type __int32_t = i32;
let mut sign: int32_t = 0x80000000 as int32_t;
```
which causes this compilation error:
```
error: literal out of range for `i32`
  --> src/mathd/sqrtd.rs:42:29
   |
42 |     let mut sign: int32_t = 0x80000000 as int32_t;
   |                             ^^^^^^^^^^
   |
   = note: `#[deny(overflowing_literals)]` on by default
   = note: the literal `0x80000000` (decimal `2147483648`) does not fit into the type `i32` and will become `-2147483648i32`
   = help: consider using the type `u32` instead
```
C2Rust 0.20.0 translates that to:
```rust
pub type int32_t = __int32_t;
pub type __int32_t = libc::c_int;
let mut sign: int32_t = 0x80000000 as libc::c_uint as int32_t;
```
which compiles.

### PR DESCRIPTION
**Pull request by kkysen**
* Fixes #1435.
* Supersedes #1436.

This first reverts the part of 7eaa39f that broke #1435, which is omitting casts from literals where the type already matches without checking if the literal is within that type's range.  Then tests are added and then `fn literal_kind_matches_ty` is fixed to also check the type's range.  If the literal may be out of range on any possible platform, then a cast remains.

I didn't add a float to these tests since floats go through a different code path (there's no cast generated for them).  So for them, we need to explicitly generate a cast if it's out of range.

### CODE REVIEW

File: c2rust-transpile/src/translator/literals.rs [hunk 1]
```diff
@@ -72,16 +72,18 @@ impl<'c> Translation<'c> {
         mk().cast_expr(value, target_ty)
     }
 
-    /// Return whether the literal can be directly translated as this type. This does not check
-    /// that the literal fits into the type's range of values (as doing so is in general dependent
-    /// on the target platform), just that it is the appropriate kind for the type.
+    /// Return whether the literal can be directly translated as this type.
     pub fn literal_kind_matches_ty(&self, lit: &CLiteral, ty: CQualTypeId) -> bool {
```
Comment (fw-immunant) [inline c2rust-transpile/src/translator/literals.rs]: At this point, a name like `literal_matches_ty` would make more sense as it's now analyzing the value, not just the kind.

**Comment by fw-immunant** [comment]
For CI, looks like a macOS snapshot needs updating.

File: c2rust-transpile/src/c_ast/mod.rs [hunk 2]
```diff
@@ -2183,6 +2183,177 @@ impl CTypeKind {
...
+            Int64 => in_range::<i64>(value),
+            Int128 => in_range::<i128>(value),
+
+            UInt8 => in_range::<u8>(value),
+            UInt16 => in_range::<u16>(value),
+            UInt32 => in_range::<u32>(value),
+            UInt64 => in_range::<u64>(value),
+            UInt128 => in_range::<u128>(value),
+
+            // There's no guarantee on pointer size, but `NULL` should work.
```
Comment (ahomescu) [inline c2rust-transpile/src/c_ast/mod.rs:2238]: It's guaranteed to be at least as large as a `u16`, but I'm not sure that's useful here. It's rare that you'll need a constant pointer that's within the first 64KB.

Edit: Never mind, I realized this is for C pointers.

File: c2rust-transpile/src/c_ast/mod.rs [hunk 3]
```diff
@@ -2183,6 +2183,177 @@ impl CTypeKind {
...
+            Short => in_range::<i16>(value),
+            Int => in_range::<i16>(value),
+            Long => in_range::<i32>(value),
+            LongLong => in_range::<i64>(value),
+
+            // `unsigned int` is at least `u16` and `unsigned long` is at least `u32`.
+            UChar => in_range::<u8>(value),
+            UShort => in_range::<u16>(value),
+            UInt => in_range::<u16>(value),
+            ULong => in_range::<u32>(value),
```
Comment (ahomescu) [inline c2rust-transpile/src/c_ast/mod.rs:2223]: Depends on the ABI: LP64 (Linux and macOS) also uses 64 bits for `long`, while Windows uses 32. If you're just being conservative here and trying to handle all platforms, I'd add a comment here.

Comment (kkysen) [reply c2rust-transpile/src/c_ast/mod.rs:2223]: Oh, is this not enough?  I can try to add more from the PR description, where I explained more.

```rust
    /// Whether `value` is guaranteed to be in this integer type's range.
    /// Thus, minimum ranges are used (e.x. [`i16::MIN`] for [`Self::Int`]).
```

File: c2rust-transpile/src/c_ast/mod.rs [hunk 4]
```diff
@@ -2183,6 +2183,177 @@ impl CTypeKind {
...
+            IntMax => in_range::<i64>(value),
+            UIntMax => in_range::<u64>(value),
+
+            // `size_t` is at least a `u16`, and similar for `ssize_t` and `ptrdiff_t`.
+            Size => in_range::<u16>(value),
+            SSize => in_range::<i16>(value),
+            PtrDiff => in_range::<i16>(value),
+
+            // Floats, see `Self::guaranteed_float_in_range`.
+            Float => false,
```
Comment (ahomescu) [inline c2rust-transpile/src/c_ast/mod.rs:2251]: Technically this still works if the integer fits into the mantissa, i.e., 24 bits.

File: c2rust-transpile/src/c_ast/mod.rs [hunk 5]
```diff
@@ -2183,6 +2183,177 @@ impl CTypeKind {
...
+            Double => false,
```
Comment (ahomescu) [inline c2rust-transpile/src/c_ast/mod.rs:2252]: Larger mantissa here: 53 bits.

File: c2rust-transpile/src/c_ast/mod.rs [hunk 6]
```diff
@@ -2183,6 +2183,177 @@ impl CTypeKind {
...
+            ConstantArray(_, _) => false,
+            IncompleteArray(_) => false,
+            VariableArray(_, _) => false,
+            TypeOf(_) => false,
+            TypeOfExpr(_) => false,
+            Function(_, _, _, _, _) => false,
+            Typedef(_) => false,
+            Decayed(_) => false,
+            Elaborated(_) => false,
+            Paren(_) => false,
```
Comment (ahomescu) [inline c2rust-transpile/src/c_ast/mod.rs:2271]: Couldn't this be recursive?

File: c2rust-transpile/src/translator/literals.rs [hunk 7]
```diff
@@ -72,16 +72,18 @@ impl<'c> Translation<'c> {
...
         let ty_kind = &self.ast_context.resolve_type(ty.ctype).kind;
         match *lit {
-            CLiteral::Integer(..) if ty_kind.is_integral_type() && !ty_kind.is_bool() => true,
+            CLiteral::Integer(value, _) if ty_kind.is_integral_type() && !ty_kind.is_bool() => {
```
Comment (ahomescu) [inline c2rust-transpile/src/translator/literals.rs:77]: You handle `Bool` in the `guaranteed_integer_in_range`, why is the `is_bool` check here?

File: c2rust-transpile/src/c_ast/mod.rs (hunk 4 above)
Comment (kkysen) [reply c2rust-transpile/src/c_ast/mod.rs:2251]: It's not meant to be called on floats at all.

File: c2rust-transpile/src/c_ast/mod.rs (hunk 6 above)
Comment (kkysen) [reply c2rust-transpile/src/c_ast/mod.rs:2271]: It's only meant to be called on integers.

File: c2rust-transpile/src/translator/literals.rs (hunk 7 above)
Comment (kkysen) [reply c2rust-transpile/src/translator/literals.rs:77]: I can remove it from `fn guaranteed_integer_in_range` if that's clearer. It's handled differently here.

File: c2rust-transpile/src/translator/literals.rs (hunk 1 above)
Comment (kkysen) [reply c2rust-transpile/src/translator/literals.rs]: Good point.  Fixed in c91d5ef.

File: c2rust-transpile/src/c_ast/mod.rs (hunk 4 above)
Comment (ahomescu) [reply c2rust-transpile/src/c_ast/mod.rs:2251]: Couldn't it be called on something like `123456 as f32`?

Comment (kkysen) [reply c2rust-transpile/src/c_ast/mod.rs:2251]: No, we never go down that code path.

File: c2rust-transpile/src/c_ast/mod.rs (hunk 3 above)
Comment (ahomescu) [reply c2rust-transpile/src/c_ast/mod.rs:2223]: Yeah you could elaborate a bit, maybe add a line on where differences could come from.

File: c2rust-transpile/src/c_ast/mod.rs (hunk 4 above)
Comment (ahomescu) [reply c2rust-transpile/src/c_ast/mod.rs:2251]: Got it, that's surprising.

File: c2rust-transpile/src/c_ast/mod.rs (hunk 3 above)
Comment (kkysen) [reply c2rust-transpile/src/c_ast/mod.rs:2223]: Clarified the docs in 2e94402.

File: c2rust-transpile/src/c_ast/mod.rs (hunk 4 above)
Comment (kkysen) [reply c2rust-transpile/src/c_ast/mod.rs:2251]: Clarified in the docs in 813e8e3.

File: c2rust-transpile/src/translator/literals.rs (hunk 7 above)
Comment (kkysen) [reply c2rust-transpile/src/translator/literals.rs:77]: Removed in bc89539.
